# Generated by Django 5.0.6 on 2024-06-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
